POST http://localhost:2525/imposters

{
  "port": 5053,
  "protocol": "http",
  "stubs": [{
    "responses": [
      { "is": { "statusCode": 200,
                "body":{
                    "cars": [""]
                } }}
    ],
    "predicates": [{
      "and": [
        {
          "equals": {
            "path": "/api/cars",
            "method": "GET"
          }
        }
      ]
     }
    ]
   }
  ]
}