POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 5056,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "equals": {
            "method": "POST",
            "path": "/api/users"
          }
        },
        {
          "equals": {
            "headers": {
              "Content-Type": "application/json"
            }
          }
        },
        {
          "contains": {
            "body": "\"email\":\"exists@example.com\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": { "Content-Type": "application/json" },
            "body": "{ \"error\": \"email_exists\", \"message\": \"O email já está registado\" }"
          }
        }
      ]
    }
  ]
}